package model;

public enum CommandType {
    FILE_MESSAGE, FILE_REQUEST, FILE_INFO, FILE_DELETE, FILE_RENAME,
    AUTH_REQUEST, AUTH_RESPONSE, DISCONNECT,
    LIST_RESPONSE, LIST_REQUEST,
    NEW_FOLDER,
}